name: Nizhny Koin CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-nizhny-koin:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      # Initialize Environment
      - run: npm config set prefix /usr/local

      # Checkout Project
      - name: Checkout code
        uses: actions/checkout@v3

      # Setup Node.JS
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          # cache: "yarn"
        env:
          NODE_OPTIONS: --max_old_space_size=4096

      # Install Dependencies
      - name: Install dependencies
        run: cd nizhny-backend && yarn install --immutable

      # Deploy to Development
      - name: Deploy to development
        run: cd nizhny-backend && yarn deploy
        env:
          stage: deploy
          REGION: eu-west-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECERT_ACCESS_KEY }}
